import { ChakraProvider, extendTheme } from '@chakra-ui/react'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { QueryClient, QueryClientProvider } from 'react-query'
import 'reset-css'
import 'slick-carousel/slick/slick-theme.css'
import 'slick-carousel/slick/slick.css'
import { Footer } from '../components/Footer'
import { Menu } from '../components/Menu'

const queryClient = new QueryClient({
  defaultOptions: { queries: { refetchOnWindowFocus: false, refetchOnReconnect: false } },
})
const theme = extendTheme({
  styles: {
    global: {
      'body, html': { backgroundColor: 'ivory' },
      html: { overflowX: 'hidden' },
      'a:hover': { textDecoration: 'none!important' },
    },
  },
})

const MyApp = ({ Component, pageProps }: AppProps) => {
  return (
    <QueryClientProvider client={queryClient}>
      <ChakraProvider theme={theme}>
        <Head>
          <title>Five Hundred</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="twitter:card" content="summary" />
          <meta name="twitter:site" content="@dani" />
          <meta name="twitter:title" content="Example Webpage Title" />
          <meta name="twitter:description" content="Example Webpage Description" />
          <meta name="twitter:image" content="/path_to_your_preview_image.png" />
          <meta name="twitter:image:alt" content="alt text of your image" />
          <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Menu />
        <Component {...pageProps} />
        <Footer />
      </ChakraProvider>
    </QueryClientProvider>
  )
}

export default MyApp
